# TruffleHog Configuration
# See: https://github.com/trufflesecurity/trufflehog

# Paths to exclude from scanning
exclude_paths:
  - "venv/**"
  - ".venv/**"
  - "node_modules/**"
  - "__pycache__/**"
  - ".pytest_cache/**"
  - ".git/**"
  - "*.log"
  - "reports/**"
  - "htmlcov/**"
  - "*.json"
  - "*.xml"

# Detectors to disable (optional)
# exclude_detectors:
#   - "URI"
#   - "Base64"

# Only scan for verified secrets (reduces false positives)
# Note: This is set via command line args in the workflow