apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-app
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: taskflow
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"