apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: taskflow-prod

namespace: taskflow

resources:
  - ../../base

labels:
  - pairs:
      environment: production

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: taskflow-app
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: taskflow-config

images:
  - name: taskflow
    newTag: v1.0.0