---
all:
  children:
    development:
      hosts:
        dev-k8s-master:
          ansible_host: localhost
          ansible_connection: local
          environment: development
          k8s_namespace: taskflow-dev
          k8s_context: k3d-taskflow-dev
      vars:
        deployment_replicas: 1
        resource_requests_cpu: "50m"
        resource_requests_memory: "64Mi"
        resource_limits_cpu: "100m"
        resource_limits_memory: "128Mi"
        
    staging:
      hosts:
        staging-k8s-master:
          ansible_host: staging.taskflow.local
          ansible_user: ubuntu
          environment: staging
          k8s_namespace: taskflow-staging
          k8s_context: taskflow-staging
      vars:
        deployment_replicas: 2
        resource_requests_cpu: "100m"
        resource_requests_memory: "128Mi"
        resource_limits_cpu: "200m"
        resource_limits_memory: "256Mi"
        
    production:
      hosts:
        prod-k8s-master:
          ansible_host: prod.taskflow.local
          ansible_user: ubuntu
          environment: production
          k8s_namespace: taskflow
          k8s_context: taskflow-production
      vars:
        deployment_replicas: 3
        resource_requests_cpu: "200m"
        resource_requests_memory: "256Mi"
        resource_limits_cpu: "500m"
        resource_limits_memory: "512Mi"
        hpa_enabled: true
        
    monitoring:
      hosts:
        monitoring-server:
          ansible_host: monitoring.taskflow.local
          ansible_user: ubuntu
          environment: monitoring
          k8s_namespace: taskflow-monitoring
      vars:
        prometheus_retention: "15d"
        grafana_admin_password: "{{ vault_grafana_admin_password }}"
        
  vars:
    # Global variables
    app_name: taskflow
    app_version: latest
    container_registry: ghcr.io
    container_image: "{{ container_registry }}/taskflow/taskflow"
    
    # Database configuration
    database_path: "/app/data/taskflow.db"
    database_backup_enabled: true
    database_backup_retention: "7d"
    
    # Security settings
    security_scan_enabled: true
    security_fail_on_critical: true
    security_tools:
      - trivy
      - bandit
      - safety
      - semgrep
    
    # Monitoring configuration
    monitoring_enabled: true
    prometheus_port: 9090
    grafana_port: 3000
    metrics_path: "/metrics"
    
    # Deployment configuration
    deployment_strategy: RollingUpdate
    rolling_update_max_surge: 1
    rolling_update_max_unavailable: 0
    health_check_path: "/docs"
    health_check_port: 8000
    
    # Backup configuration
    backup_enabled: true
    backup_schedule: "0 2 * * *"  # Daily at 2 AM
    backup_retention_days: 7