apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    environment: {{ .Values.config.environment }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"