apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.secretKey }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}