apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
  labels:
    app.kubernetes.io/name: taskflow
    app.kubernetes.io/component: config
data:
  DATABASE_PATH: "/app/data/taskflow.db"
  PYTHONPATH: "/app"
  ENVIRONMENT: "kubernetes"
  APP_NAME: "TaskFlow"
  APP_VERSION: "1.0.0"