apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: taskflow-base

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: taskflow
      app.kubernetes.io/managed-by: kustomize

images:
  - name: taskflow
    newTag: latest