apiVersion: v1
kind: PersistentVolume
metadata:
  name: taskflow-pv
  labels:
    app.kubernetes.io/name: taskflow
    app.kubernetes.io/component: storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/taskflow-data
    type: DirectoryOrCreate