apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secret
  namespace: taskflow
  labels:
    app.kubernetes.io/name: taskflow
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Base64 encoded values
  # To generate: echo -n "your-secret-key" | base64
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  JWT_SECRET: and0LXNlY3JldC1rZXktZm9yLWp3dC10b2tlbnM=