apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: taskflow
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"